import { defineField, defineType } from "sanity";

export const postSchema = defineType({
  name: "post",
  title: "Post",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required().min(20).max(80),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "metaDescription",
      title: "Meta description",
      type: "text",
      rows: 3,
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: "targetKeyword",
      title: "Target keyword",
      type: "string",
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "reference",
      to: [{ type: "author" }],
    }),
    defineField({
      name: "generatedBy",
      title: "Generated by",
      type: "string",
      readOnly: true,
    }),
    defineField({
      name: "airtableClientId",
      title: "Airtable client ID",
      type: "string",
      readOnly: true,
    }),
    defineField({
      name: "generatedAt",
      title: "Generated at",
      type: "datetime",
      readOnly: true,
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "targetKeyword" },
  },
});
